export const ColumnsCardData = [
  {
    columnName: '3 Novos atendimentos',
    idx: 0,
    cards: [
      {
        name: 'Flávio Mendes Campos',
        timeStamp: '03 Dez • 7:44',
        subTitle: 'Origem – destino',
        subInfo: 'Cuiabá, MT – Salvador, BA',
        tagInfo: 'TTU',
        idx: '1a',
      },
      {
        name: 'Joana Alves Teixeira',
        timeStamp: '03 Dez • 7:44',
        subTitle: 'Origem – destino',
        subInfo: 'São Paulo, SP – Petrópolis, RJ',
        tagInfo: 'AE',
        idx: '2a',
      },
    ],
  },
  {
    columnName: '4 Vagas a confirmar',
    idx: 1,
    cards: [
      {
        name: 'Flávio Mendes Campos',
        timeStamp: '03 Dez • 7:44',
        subTitle: 'Em espera',
        subInfo: '12h 4m',
        tagInfo: 'TA',
        idx: '1b',
        style: 'danger',
      },
      {
        name: 'Joana Alves Teixeira',
        timeStamp: '03 Dez • 7:44',
        subTitle: 'Em espera',
        subInfo: '2h 2m',
        tagInfo: 'TT',
        idx: '2b',
        style: 'danger',
      },
      {
        name: 'Renato Moreria',
        timeStamp: '03 Dez • 12:10',
        subTitle: 'Em espera',
        subInfo: '56min',
        tagInfo: 'TT',
        idx: '3b',
        style: 'warning',
      },
      {
        name: 'Marcelo Almeida Lopes',
        timeStamp: '03 Dez • 8:33',
        subTitle: 'Em espera',
        subInfo: '12min',
        tagInfo: 'TA',
        idx: '4b',
        style: 'primary',
      },
      {
        name: 'Marcelo Almeida Lopes',
        timeStamp: '03 Dez • 8:33',
        subTitle: 'Em espera',
        subInfo: '12min',
        tagInfo: 'TA',
        idx: '5b',
        style: 'primary',
      },
      {
        name: 'Marcelo Almeida Lopes',
        timeStamp: '03 Dez • 8:33',
        subTitle: 'Em espera',
        subInfo: '12min',
        tagInfo: 'TA',
        idx: '6b',
        style: 'primary',
      },
      {
        name: 'Marcelo Almeida Lopes',
        timeStamp: '03 Dez • 8:33',
        subTitle: 'Em espera',
        subInfo: '12min',
        tagInfo: 'TA',
        idx: '7b',
        style: 'primary',
      },
      {
        name: 'Marcelo Almeida Lopes',
        timeStamp: '03 Dez • 8:33',
        subTitle: 'Em espera',
        subInfo: '12min',
        tagInfo: 'TA',
        idx: '8b',
        style: 'primary',
      },
      {
        name: 'Marcelo Almeida Lopes',
        timeStamp: '03 Dez • 8:33',
        subTitle: 'Em espera',
        subInfo: '12min',
        tagInfo: 'TA',
        idx: '9b',
        style: 'primary',
      },
    ],
  },
  {
    columnName: '5 Planejamento de transportes',
    idx: 2,
    cards: [
      {
        name: 'José Augusto Marques',
        timeStamp: '03 Dez • 7:44',
        subTitle: 'Origem – destino',
        subInfo: 'Parado',
        tagInfo: 'TA',
        idx: '1c',
        style: 'danger',
      },
      {
        name: 'Joana Alves Teixeira',
        timeStamp: '03 Dez • 7:44',
        subTitle: 'Origem – destino',
        subInfo: 'Ag. vaga',
        tagInfo: 'AE',
        idx: '2c',
        style: 'warning',
      },
      {
        name: 'Flávio Mendes Campos',
        timeStamp: '03 Dez • 7:44',
        subTitle: 'Origem – destino',
        subInfo: 'Em andamento',
        tagInfo: 'AE',
        idx: '3c',
        style: 'primary',
      },
    ],
  },
];
